- link:
    ~/.config/fish/config.fish: shells/fish/config.fish
    ~/.config/fish/fishfile: shells/fish/fishfile
    ~/.config/fish/conf.d/addpath.fish: shells/fish/addpath.fish

- shell:
  - command: |
      fish -c \
      'if not functions -q fisher
          curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
      else
          fisher self-update
      end'
    description: Installing/Updating Fisher
  - [fish -c fisher, Updating fish plugins]
