- link:
    ~/Brewfile: tools/homebrew/Brewfile

- brewfile:
  - ~/Brewfile

- shell:
  - [brew update, Updating Homebrew]
  - [brew upgrade, Upgrading outdated brews]
  - [brew cask upgrade, Upgrading outdated casks]
  - [brew gem install colorls, Installing colorls gem]
  - [brew cleanup, Cleanup brew cached downloads]
