- shell:
  - [echo 'eval (pipenv --completion)' > ~/.config/fish/completions/pipenv.fish, Adding pipenv fish completions]
  - [poetry completions fish > ~/.config/fish/completions/poetry.fish, Adding poetry fish completions]
  - [mkdir -p ~/.zfunc && poetry completions zsh > ~/.zfunc/_poetry, Adding poetry Zsh completions]
  - [pyenv rehash, Rehashing pyenv shims]
