- shell:
  - command: |
      if command -v poetry >/dev/null 2>&1; then
        poetry self:update
      else
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
      fi
    description: Installing poetry
  - [echo 'eval (pipenv --completion)' > ~/.config/fish/completions/pipenv.fish, Adding pipenv fish completions]
  - [poetry completions fish > ~/.config/fish/completions/poetry.fish, Adding poetry fish completions]
  - [mkdir -p ~/.zfunc && poetry completions zsh > ~/.zfunc/_poetry, Adding poetry Zsh completions]
  - [poetry config settings.virtualenvs.in-project true, Setting poetry configuration variable]
  - [pyenv rehash, Rehashing pyenv shims]
