version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 99
    assignees:
      - klane
    labels:
      - dependencies
      - submodules
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 99
    assignees:
      - klane
    labels:
      - dependencies
      - actions
