# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'getantibody/tap'

# Shells
brew 'fish'
brew 'zsh'
brew 'antibody'
brew 'starship'

# Programming Languages
cask 'java8'
brew 'python'
brew 'r'
brew 'ruby'
brew 'rust'
brew 'rustup'

# Utilities
brew 'brew-gem'
brew 'direnv'
brew 'gnupg'
brew 'mas'
brew 'openssh'
brew 'pinentry-mac'

# Programming Tools
brew 'diff-so-fancy'
brew 'git'
brew 'gradle'
brew 'hub'
brew 'legit'
brew 'travis'

# Python Tools
brew 'black'
brew 'flake8'
brew 'mkdocs'
brew 'mypy'
brew 'pipenv'
brew 'pyenv'

# Support Casks
cask 'xquartz'

# IDEs & Editors
cask 'jetbrains-toolbox'
cask 'rstudio'
cask 'sublime-text'
cask 'visual-studio-code'

# Images
brew 'imagemagick'
cask 'gimp'
cask 'icons8'
cask 'inkscape'

# Casks
cask 'cakebrew'
cask 'dashlane'
cask 'db-browser-for-sqlite'
cask 'flux'
cask 'font-meslo-nerd-font'
cask 'foxitreader'
cask 'gitkraken'
cask 'google-chrome'
cask 'hyper'
cask 'iterm2'
cask 'keepingyouawake'
cask 'mactex'
cask 'slack'
cask 'spotify'
cask 'steam'
