#!/usr/bin/env bash

# function to echo green text
function gecho() {
    echo "$(tput setaf 2)$1$(tput sgr0)"
}

gecho 'Updating Homebrew'
brew update

gecho 'Upgrading outdated brews'
brew upgrade

gecho 'Upgrading outdated casks'
brew cask upgrade

gecho 'Installing missing packages'
brew bundle check --file=~/Brewfile || brew bundle --file=~/Brewfile

gecho 'Installing colorls gem'
if [ "$(brew list gem-colorls)" ]; then
    brew gem upgrade colorls || true
else
    brew gem install colorls
fi

gecho 'Cleanup brew cached downloads'
brew cleanup
