# Taps
tap 'homebrew/cask' if OS.mac?
tap 'homebrew/cask-fonts' if OS.mac?
tap 'homebrew/cask-versions' if OS.mac?
tap 'getantibody/tap'

# Dupes
brew 'coreutils'
brew 'curl'
brew 'diffutils'
brew 'findutils'
brew 'gawk'
brew 'gnu-sed'
brew 'gnu-which'
brew 'grep'
brew 'make'
brew 'rsync'
brew 'wget'

# Utilities
brew 'bat'
brew 'exa'
brew 'fasd'
brew 'fd'
brew 'fselect'
brew 'fzf'
brew 'htop'
brew 'hyperfine'
brew 'rename'
brew 'ripgrep'
brew 'sd'
brew 'speedtest-cli'
brew 'thefuck'
brew 'tmux'
brew 'tokei'

# macOS Utilities
brew 'mas' if OS.mac?
brew 'osxutils' if OS.mac?
brew 'pinentry-mac' if OS.mac?
brew 'trash' if OS.mac?

# Information Utilities
brew 'howdoi'
brew 'tldr'
brew 'wtf'

# Shells
brew 'fish'
brew 'zsh'
brew 'antibody'
brew 'starship'

# Programming Languages
brew 'go'
cask 'java8'
brew 'python'
brew 'r'
brew 'rustup'

# Utilities
brew 'direnv'
brew 'gnupg'
brew 'openssh'

# Programming Tools
brew 'asdf'
brew 'diff-so-fancy'
brew 'git'
brew 'gitup'
brew 'ghi'
brew 'ghq'
brew 'gradle'
brew 'hub'
brew 'lazygit'
brew 'legit'
brew 'pre-commit'
brew 'travis'

# Python Tools
brew 'black'
brew 'flake8'
brew 'mkdocs'
brew 'mypy'
brew 'pipenv'

# Support Casks
cask 'xquartz'

# IDEs & Editors
cask 'jetbrains-toolbox'
cask 'rstudio'
cask 'sublime-text'
cask 'visual-studio-code'

# Images
brew 'imagemagick'
cask 'gimp'
cask 'icons8'
cask 'inkscape'

# Casks
cask 'boostnote'
cask 'cakebrew'
cask 'cheatsheet'
cask 'dash'
cask 'dashlane'
cask 'db-browser-for-sqlite'
cask 'flux'
cask 'font-meslo-nerd-font'
cask 'foxitreader'
cask 'gitkraken'
cask 'google-chrome'
cask 'hyper'
cask 'iterm2'
cask 'keepingyouawake'
cask 'mactex'
cask 'slack'
cask 'spotify'
cask 'steam'
