#!/usr/bin/env bash

# function to echo green text
function gecho() {
    echo "$(tput setaf 2)$1$(tput sgr0)"
}

gecho 'Updating Homebrew'
brew update

gecho 'Upgrading outdated brews'
brew upgrade

if [ "$(uname)" == "Darwin" ]; then
    gecho 'Upgrading outdated casks'
    brew cask upgrade
fi

gecho 'Installing missing packages'
brew bundle check --file=~/Brewfile || brew bundle --file=~/Brewfile

gecho 'Cleanup brew cached downloads'
brew cleanup
