#!/usr/bin/env bash

echo 'Updating Homebrew'
brew update

echo 'Upgrading outdated brews'
brew upgrade

echo 'Upgrading outdated casks'
brew cask upgrade

echo 'Installing missing packages'
brew bundle check --file=~/Brewfile || brew bundle --file=~/Brewfile

echo 'Installing colorls gem'
if [ "$(brew list gem-colorls)" ]; then
    brew gem upgrade colorls || true
else
    brew gem install colorls
fi

echo 'Cleanup brew cached downloads'
brew cleanup
