version: 1
update_configs:
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
      - "submodules"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
      - "actions"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
