#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(dirname ${META_DIR})"

PLUGIN_DIR="${META_DIR}/plugins"
CONFIG_DIR="${META_DIR}/configs"
PROFILES_DIR="${META_DIR}/profiles"

DOTBOT_DIR="${META_DIR}/dotbot"
DOTBOT_BIN="bin/dotbot"

cd "${BASE_DIR}"
git submodule update --init --recursive --remote

for config in ${@}; do
    configFile="$(mktemp)" ; echo -e "$(<"${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${CONFIG_DIR}/${config}${CONFIG_SUFFIX}")" > "$configFile"
    "${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir "${PLUGIN_DIR}/dotbot-*" -c "$configFile" ; rm -f "$configFile"
done
