#!/usr/bin/env bash

set -e

META_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILE_DIR="${META_DIR}/profiles"

while IFS= read -r config; do
    CONFIGS+=" ${config}"
done < "${PROFILE_DIR}/$1"

echo "Configs in $1:${CONFIGS}"

"${META_DIR}/install-config" "${CONFIGS}"
