- link:
    ~/.config/fish/config.fish: shells/fish/config.fish
    ~/.config/fish/fishfile: shells/fish/fishfile
    ~/.config/fish/conf.d/addpath.fish: shells/fish/addpath.fish
    ~/.config/fish/functions/gcd.fish: shells/fish/functions/gcd.fish
    ~/.config/fish/functions/replace.fish: shells/fish/functions/replace.fish
    ~/.config/starship.toml: shells/starship/starship.toml

- shell:
  - [$DOTFILES/shells/fish/install-fisher, Installing Fisher]
  - [fish -c fisher, Updating fish plugins]
