- link:
    ~/.condarc: tools/python/condarc
    ~/.config/flake8: tools/python/flake8

- asdf:
  - plugin: python
    versions:
      - latest:2.7
      - latest:3.4
      - latest:3.5
      - latest:3.6
      - latest:3.7
      - latest:3.8

- shell:
  - [$DOTFILES/tools/python/install-poetry, Installing poetry]
  - [echo 'eval (pipenv --completion)' > ~/.config/fish/completions/pipenv.fish, Adding pipenv fish completions]
  - [poetry completions fish > ~/.config/fish/completions/poetry.fish, Adding poetry fish completions]
  - [mkdir -p ~/.zfunc && poetry completions zsh > ~/.zfunc/_poetry, Adding poetry Zsh completions]
  - [poetry config virtualenvs.in-project true, Setting poetry configuration variable]
  - [asdf reshim, Recreating asdf shims]
