name: Format

on: push

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Linting
        uses: pre-commit/action@v1.0.0
