name: Format

on: push

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
      - name: Hash Python version
        id: hash
        run: echo ::set-output name=hash::$(python --version | sha256sum | cut -d' ' -f1)
      - name: Restore cache
        uses: actions/cache@v3.2.6
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ steps.hash.outputs.hash }}|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit|${{ steps.hash.outputs.hash }}
      - name: Linting
        uses: pre-commit/action@v2.0.3
