name: Format

on: push

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Linting
        run: |
          pip install pre-commit
          pre-commit install-hooks
          pre-commit run --all-files
